### ISSUE TITLE
Uncaught TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by lenage** [lenage/language-coursescript#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [language-coursescript](https://github.com/lenage/language-coursescript) package 3.3.0

### Stack Trace

Uncaught TypeError: Data must be a string or a buffer

```
At /Users/lenage/.atom/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:17

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:74:16)
    at Clipboard.md5 (/Applications/Atom.app/Contents/Resources/app/src/clipboard.js:41:49)
    at Clipboard.write (/Applications/Atom.app/Contents/Resources/app/src/clipboard.js:52:44)
    at LanguageCoursescriptSearch.handleCopy (/packages/language-coursescript/lib/language-coursescript-search.js:20:20)
    at handleCopy (/packages/language-coursescript/components/SearchItem.jsx:19:7)
    at onClick (/packages/language-coursescript/components/SearchItem.jsx:12:28)
    at Object.ia (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:15:131)
    at Object.invokeGuardedCallback (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:16:137)
    at Object.invokeGuardedCallbackAndCatchFirstError (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:16:249)
    at za (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:20:288)
    at Da (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:22:174)
    at Fa (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:22:335)
    at Ba (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:21:248)
    at Ia (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:24:79)
    at Ja (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:24:244)
    at Fd (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:88:254)
    at Yh (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:221:195)
    at Wb (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:44:362)
    at Kd (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:89:372)
    at interactiveUpdates (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:225:368)
    at Jd (/packages/language-coursescript/node_modules/react-dom/cjs/react-dom.production.min.js:89:113)
```

### Commands

```
  2x -1:26.2.0 language-coursescript:search (input.hidden-input)
     -1:13.9.0 editor:consolidate-selections (input.hidden-input)
     -1:13.9.0 language-coursescript:search-close (input.hidden-input)
     -1:13 core:undo (input.hidden-input)
     -1:11.3.0 language-coursescript:search (input.hidden-input)
  3x -0:48.3.0 core:select-all (input.native-key-bindings)
```

### Non-Core Packages

```
busy-signal 1.4.3 
go-debug 1.5.1 
go-plus 5.5.5 
go-signature-statusbar 1.2.3 
hyperclick 0.1.3 
intentions 1.1.5 
language-bazel 0.3.4 
language-coursescript 3.3.0 
linter 2.2.0 
linter-ui-default 1.6.8 
minimap 4.29.6 
multi-cursor 2.1.5 
terminal-plus 0.14.5 
```

**Comment by Bill0106** [comment]
fixed [#21](https://github.com/lenage/language-coursescript/pull/21)
