### ISSUE TITLE
ISSUE SOLVED-Failed to activate the language-coursescript package-

### ISSUE THREAD

**Issue by hao-xue** [lenage/language-coursescript#27]
Issue solved by reinstalling atom package. Many thanks!

--------------Original issue------------
I tried to preview on Atom but the same error keeps popping up. Please help.

[Enter steps to reproduce:]

1. Open terminal (/Application/Utilities/Terminal.app)
2. Download shell script atom_preview.sh
3. Execute shell script
4. Open Atom and try to preview

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Mac OS X 10.13.5
**Thrown From**: [language-coursescript](https://github.com/lenage/language-coursescript) package 3.3.5

### Stack Trace

Failed to activate the language-coursescript package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-coursescript/lib/language-coursescript-view.js:3:31)
    at /packages/language-coursescript/lib/language-coursescript-view.js:9:46)
    at Module.get_Module._compile (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-coursescript/lib/language-coursescript.js:4:22)
    at /packages/language-coursescript/lib/language-coursescript.js:119:2)
    at Module.get_Module._compile (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at CommandRegistry.handleCommandEvent (/private/var/folders/zr/z06whfg56ys4gncvdfnhrbgw0000gp/T/AppTranslocation/BBD74F95-5DC5-4F45-B676-FEA7DB48CEBE/d/Atom.app/Contents/Resources/app/src/command-registry.js:360:24)
```

### Commands

```
     -0:22.6.0 language-coursescript:preview (span.syntax--source.syntax--coursescript)
```

### Non-Core Packages

```
git-plus 8.0.0 
language-coursescript 3.3.5 
```

**Comment by Bill0106** [comment]
Looks like the 'atom-space-pen-views' dependency is not installed.
Please reinstall the atom package.
Then the problem should be resolved.

**Comment by guangleiz** [comment]
The problem already been fixed by restarting ATOM. @hao-xue please confirm and close this ticket.
